Code optimization.
apache/iotdb-client-go pull request #18
Opened 2021-03-15 05:59 UTC by manlge

2021-04-06 02:40 UTC, ericpai commented
Is this PR ready for reviewing? I'm familiar with Golang. I can help to do this...

2021-04-06 02:51 UTC, ericpai requested changes

2021-04-06 02:51 UTC, ericpai commented on client/session.go
> +			switch v := v.(type) {
It's better to not shadow the variable `v`. `v`'s type is `interface{}`. I suggest that we use a different variable name like `dv` instead of `v`.

2021-04-06 13:03 UTC, jixuan1989 commented
Thanks @ericpai ,
After merging this PR and fix iotdb-2934, I will add tag v0.12.0.

2021-04-07 02:23 UTC, ericpai approved these changes
LGTM

2021-04-07 03:38 UTC, merged

2021-04-07 03:39 UTC, jixuan1989 commented
Thanks, @manlge  and @ericpai .
For future PRs, better to add descriptions.